### PR TITLE
Updated packages. Added dependabot and gitlab workflow

### PR DESCRIPTION
**Pull request by lodmfjord**
I needed to update **esbuild** to be able to use **ts-eager** on M1.

Also added, to make updates like this less painful in the future:

- dependabot. 
- github workflow with test and linter for pull requests.

### CODE REVIEW

**Comment by lodmfjord** [comment]
ignore the massive amount of commits. Sorry.

**Review by raikusy — APPROVED** [review]
Great! This should be merged, also esbuild should be updated to latest version along with typescript.

Thanks!

**Comment by raikusy** [comment]
@mhart Could you please look into this, also update esbuild and typescript to latest version?
Thanks a lot for this awesome library ✌️

**Comment by lodmfjord** [comment]
Any news on this?

**Comment by mhart** [comment]
Hey all – sorry for the delay, I've been taking a bit of a break from open source.

Thanks so much for this PR – I ended up updating the deps I wanted to myself (and fixing a minor decorator issue along the way).

I've just published v2.0.0 which supports the latest esbuild version (v0.11.20). Let me know if that works for you!

**Pull request closed without merging**
